package io.github.kartoffell.KLVulkan;
import io.github.kartoffell.KLVulkan.*;
import java.lang.foreign.*;
import java.lang.invoke.*;
import java.util.function.*;
import java.nio.file.*;
import java.io.*;
import org.jspecify.annotations.*;
import org.lwjgl.system.*;
import java.nio.*;
import java.util.*;
// Copyright 2026 Kareem Athamneh
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
public enum Formats{
	VK_FORMAT_R8G8B8A8_USCALED(VK14.VkFormat.VK_FORMAT_R8G8B8A8_USCALED,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.USCALED, -1), new Component('G', 8, NumericFormat.USCALED, -1), new Component('B', 8, NumericFormat.USCALED, -1), new Component('A', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_ASTC_8x6_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x6_SRGB_BLOCK,"ASTC_8x6",16,8,6,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16(VK14.VkFormat.VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16,"64-bit B10G10R10G10",8,2,1,1,16,"","422",new Component[] {new Component('B', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1), new Component('R', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16G16_USCALED(VK14.VkFormat.VK_FORMAT_R16G16_USCALED,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.USCALED, -1), new Component('G', 16, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16,"10-bit 2-plane 422",6,1,1,1,16,"","422",new Component[] {new Component('G', 10, NumericFormat.UNORM, 0), new Component('B', 10, NumericFormat.UNORM, 1), new Component('R', 10, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(1, 2, 1, "VK_FORMAT_R10X6G10X6_UNORM_2PACK16")},null),
	VK_FORMAT_R8G8B8A8_SNORM(VK14.VkFormat.VK_FORMAT_R8G8B8A8_SNORM,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SNORM, -1), new Component('G', 8, NumericFormat.SNORM, -1), new Component('B', 8, NumericFormat.SNORM, -1), new Component('A', 8, NumericFormat.SNORM, -1)},null,new String[] {"Rgba8Snorm"}),
	VK_FORMAT_R8G8_SINT(VK14.VkFormat.VK_FORMAT_R8G8_SINT,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SINT, -1), new Component('G', 8, NumericFormat.SINT, -1)},null,new String[] {"Rg8i"}),
	VK_FORMAT_R16_SSCALED(VK14.VkFormat.VK_FORMAT_R16_SSCALED,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM(VK14.VkFormat.VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM,"8-bit 3-plane 420",3,1,1,1,0,"","420",new Component[] {new Component('G', 8, NumericFormat.UNORM, 0), new Component('B', 8, NumericFormat.UNORM, 1), new Component('R', 8, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(1, 2, 2, "VK_FORMAT_R8_UNORM"), new Plane(2, 2, 2, "VK_FORMAT_R8_UNORM")},null),
	VK_FORMAT_B8G8R8_SINT(VK14.VkFormat.VK_FORMAT_B8G8R8_SINT,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SINT, -1), new Component('G', 8, NumericFormat.SINT, -1), new Component('R', 8, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK,"ASTC_10x8",16,10,8,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R8_UINT(VK14.VkFormat.VK_FORMAT_R8_UINT,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UINT, -1)},null,new String[] {"R8ui"}),
	VK_FORMAT_R8G8B8A8_SINT(VK14.VkFormat.VK_FORMAT_R8G8B8A8_SINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SINT, -1), new Component('G', 8, NumericFormat.SINT, -1), new Component('B', 8, NumericFormat.SINT, -1), new Component('A', 8, NumericFormat.SINT, -1)},null,new String[] {"Rgba8i"}),
	VK_FORMAT_R32G32B32_SFLOAT(VK14.VkFormat.VK_FORMAT_R32G32B32_SFLOAT,"96-bit",12,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SFLOAT, -1), new Component('G', 32, NumericFormat.SFLOAT, -1), new Component('B', 32, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16,"12-bit 3-plane 444",6,1,1,1,16,"","444",new Component[] {new Component('G', 12, NumericFormat.UNORM, 0), new Component('B', 12, NumericFormat.UNORM, 1), new Component('R', 12, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(1, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(2, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16")},null),
	VK_FORMAT_R8G8B8_SINT(VK14.VkFormat.VK_FORMAT_R8G8B8_SINT,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SINT, -1), new Component('G', 8, NumericFormat.SINT, -1), new Component('B', 8, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_R8G8B8_UNORM(VK14.VkFormat.VK_FORMAT_R8G8B8_UNORM,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('B', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC6H_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_BC6H_SFLOAT_BLOCK,"BC6H",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_B8G8R8G8_422_UNORM(VK14.VkFormat.VK_FORMAT_B8G8R8G8_422_UNORM,"32-bit B8G8R8G8",4,2,1,1,0,"","422",new Component[] {new Component('B', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('R', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_EAC_R11_SNORM_BLOCK(VK14.VkFormat.VK_FORMAT_EAC_R11_SNORM_BLOCK,"EAC_R",8,4,4,1,0,"EAC","",new Component[] {new Component('R', 11, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_R32G32B32A32_UINT(VK14.VkFormat.VK_FORMAT_R32G32B32A32_UINT,"128-bit",16,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.UINT, -1), new Component('G', 32, NumericFormat.UINT, -1), new Component('B', 32, NumericFormat.UINT, -1), new Component('A', 32, NumericFormat.UINT, -1)},null,new String[] {"Rgba32ui"}),
	VK_FORMAT_B8G8R8A8_USCALED(VK14.VkFormat.VK_FORMAT_B8G8R8A8_USCALED,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.USCALED, -1), new Component('G', 8, NumericFormat.USCALED, -1), new Component('R', 8, NumericFormat.USCALED, -1), new Component('A', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R16G16_SFLOAT(VK14.VkFormat.VK_FORMAT_R16G16_SFLOAT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SFLOAT, -1), new Component('G', 16, NumericFormat.SFLOAT, -1)},null,new String[] {"Rg16f"}),
	VK_FORMAT_R8_SRGB(VK14.VkFormat.VK_FORMAT_R8_SRGB,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_BC5_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC5_UNORM_BLOCK,"BC5",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC7_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC7_UNORM_BLOCK,"BC7",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC4_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC4_UNORM_BLOCK,"BC4",8,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R4G4B4A4_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_R4G4B4A4_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('R', 4, NumericFormat.UNORM, -1), new Component('G', 4, NumericFormat.UNORM, -1), new Component('B', 4, NumericFormat.UNORM, -1), new Component('A', 4, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_10x10_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x10_UNORM_BLOCK,"ASTC_10x10",16,10,10,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R12X4G12X4_UNORM_2PACK16(VK14.VkFormat.VK_FORMAT_R12X4G12X4_UNORM_2PACK16,"32-bit",4,1,1,1,16,"","",new Component[] {new Component('R', 12, NumericFormat.UNORM, -1), new Component('G', 12, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A8B8G8R8_USCALED_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_USCALED_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.USCALED, -1), new Component('B', 8, NumericFormat.USCALED, -1), new Component('G', 8, NumericFormat.USCALED, -1), new Component('R', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16,"12-bit 2-plane 420",6,1,1,1,16,"","420",new Component[] {new Component('G', 12, NumericFormat.UNORM, 0), new Component('B', 12, NumericFormat.UNORM, 1), new Component('R', 12, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(1, 2, 2, "VK_FORMAT_R12X4G12X4_UNORM_2PACK16")},null),
	VK_FORMAT_A2R10G10B10_SNORM_PACK32(VK14.VkFormat.VK_FORMAT_A2R10G10B10_SNORM_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.SNORM, -1), new Component('R', 10, NumericFormat.SNORM, -1), new Component('G', 10, NumericFormat.SNORM, -1), new Component('B', 10, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_R16_SFLOAT(VK14.VkFormat.VK_FORMAT_R16_SFLOAT,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SFLOAT, -1)},null,new String[] {"R16f"}),
	VK_FORMAT_R16G16B16A16_SNORM(VK14.VkFormat.VK_FORMAT_R16G16B16A16_SNORM,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SNORM, -1), new Component('G', 16, NumericFormat.SNORM, -1), new Component('B', 16, NumericFormat.SNORM, -1), new Component('A', 16, NumericFormat.SNORM, -1)},null,new String[] {"Rgba16Snorm"}),
	VK_FORMAT_ASTC_12x10_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_12x10_SRGB_BLOCK,"ASTC_12x10",16,12,10,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A1R5G5B5_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_A1R5G5B5_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('A', 1, NumericFormat.UNORM, -1), new Component('R', 5, NumericFormat.UNORM, -1), new Component('G', 5, NumericFormat.UNORM, -1), new Component('B', 5, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R64G64_UINT(VK14.VkFormat.VK_FORMAT_R64G64_UINT,"128-bit",16,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.UINT, -1), new Component('G', 64, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_R16G16B16A16_UINT(VK14.VkFormat.VK_FORMAT_R16G16B16A16_UINT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UINT, -1), new Component('G', 16, NumericFormat.UINT, -1), new Component('B', 16, NumericFormat.UINT, -1), new Component('A', 16, NumericFormat.UINT, -1)},null,new String[] {"Rgba16ui"}),
	VK_FORMAT_BC2_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC2_UNORM_BLOCK,"BC2",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_6x6_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_6x6_UNORM_BLOCK,"ASTC_6x6",16,6,6,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC3_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC3_UNORM_BLOCK,"BC3",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_6x5_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_6x5_UNORM_BLOCK,"ASTC_6x5",16,6,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R64G64B64A64_UINT(VK14.VkFormat.VK_FORMAT_R64G64B64A64_UINT,"256-bit",32,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.UINT, -1), new Component('G', 64, NumericFormat.UINT, -1), new Component('B', 64, NumericFormat.UINT, -1), new Component('A', 64, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_B8G8R8_SNORM(VK14.VkFormat.VK_FORMAT_B8G8R8_SNORM,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SNORM, -1), new Component('G', 8, NumericFormat.SNORM, -1), new Component('R', 8, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_R16G16B16_UINT(VK14.VkFormat.VK_FORMAT_R16G16B16_UINT,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UINT, -1), new Component('G', 16, NumericFormat.UINT, -1), new Component('B', 16, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16(VK14.VkFormat.VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16,"64-bit G12B12G12R12",8,2,1,1,16,"","422",new Component[] {new Component('G', 12, NumericFormat.UNORM, -1), new Component('B', 12, NumericFormat.UNORM, -1), new Component('G', 12, NumericFormat.UNORM, -1), new Component('R', 12, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A8B8G8R8_SNORM_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_SNORM_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.SNORM, -1), new Component('B', 8, NumericFormat.SNORM, -1), new Component('G', 8, NumericFormat.SNORM, -1), new Component('R', 8, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_X8_D24_UNORM_PACK32(VK14.VkFormat.VK_FORMAT_X8_D24_UNORM_PACK32,"D24",4,1,1,1,32,"","",new Component[] {new Component('D', 24, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16G16B16A16_USCALED(VK14.VkFormat.VK_FORMAT_R16G16B16A16_USCALED,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.USCALED, -1), new Component('G', 16, NumericFormat.USCALED, -1), new Component('B', 16, NumericFormat.USCALED, -1), new Component('A', 16, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R64G64B64_SINT(VK14.VkFormat.VK_FORMAT_R64G64B64_SINT,"192-bit",24,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SINT, -1), new Component('G', 64, NumericFormat.SINT, -1), new Component('B', 64, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_ASTC_8x5_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x5_SRGB_BLOCK,"ASTC_8x5",16,8,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_D32_SFLOAT(VK14.VkFormat.VK_FORMAT_D32_SFLOAT,"D32",4,1,1,1,0,"","",new Component[] {new Component('D', 32, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_A8B8G8R8_UINT_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_UINT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.UINT, -1), new Component('B', 8, NumericFormat.UINT, -1), new Component('G', 8, NumericFormat.UINT, -1), new Component('R', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_B16G16R16G16_422_UNORM(VK14.VkFormat.VK_FORMAT_B16G16R16G16_422_UNORM,"64-bit B16G16R16G16",8,2,1,1,0,"","422",new Component[] {new Component('B', 16, NumericFormat.UNORM, -1), new Component('G', 16, NumericFormat.UNORM, -1), new Component('R', 16, NumericFormat.UNORM, -1), new Component('G', 16, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16(VK14.VkFormat.VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16,"64-bit R12G12B12A12",8,1,1,1,16,"","444",new Component[] {new Component('R', 12, NumericFormat.UNORM, -1), new Component('G', 12, NumericFormat.UNORM, -1), new Component('B', 12, NumericFormat.UNORM, -1), new Component('A', 12, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R8G8_USCALED(VK14.VkFormat.VK_FORMAT_R8G8_USCALED,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.USCALED, -1), new Component('G', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R32_UINT(VK14.VkFormat.VK_FORMAT_R32_UINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.UINT, -1)},null,new String[] {"R32ui"}),
	VK_FORMAT_R8_SNORM(VK14.VkFormat.VK_FORMAT_R8_SNORM,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SNORM, -1)},null,new String[] {"R8Snorm"}),
	VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK,"ASTC_6x5",16,6,5,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R16G16_UNORM(VK14.VkFormat.VK_FORMAT_R16G16_UNORM,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UNORM, -1), new Component('G', 16, NumericFormat.UNORM, -1)},null,new String[] {"Rg16"}),
	VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16,"12-bit 2-plane 444",6,1,1,1,16,"","444",new Component[] {new Component('G', 12, NumericFormat.UNORM, 0), new Component('B', 12, NumericFormat.UNORM, 1), new Component('R', 12, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(1, 1, 1, "VK_FORMAT_R12X4G12X4_UNORM_2PACK16")},null),
	VK_FORMAT_R8G8B8_USCALED(VK14.VkFormat.VK_FORMAT_R8G8B8_USCALED,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.USCALED, -1), new Component('G', 8, NumericFormat.USCALED, -1), new Component('B', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_B8G8R8A8_SINT(VK14.VkFormat.VK_FORMAT_B8G8R8A8_SINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SINT, -1), new Component('G', 8, NumericFormat.SINT, -1), new Component('R', 8, NumericFormat.SINT, -1), new Component('A', 8, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_R16G16B16A16_SFLOAT(VK14.VkFormat.VK_FORMAT_R16G16B16A16_SFLOAT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SFLOAT, -1), new Component('G', 16, NumericFormat.SFLOAT, -1), new Component('B', 16, NumericFormat.SFLOAT, -1), new Component('A', 16, NumericFormat.SFLOAT, -1)},null,new String[] {"Rgba16f"}),
	VK_FORMAT_R32G32B32_SINT(VK14.VkFormat.VK_FORMAT_R32G32B32_SINT,"96-bit",12,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SINT, -1), new Component('G', 32, NumericFormat.SINT, -1), new Component('B', 32, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK,"ASTC_10x6",16,10,6,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_ASTC_10x8_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x8_SRGB_BLOCK,"ASTC_10x8",16,10,8,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R64G64B64_SFLOAT(VK14.VkFormat.VK_FORMAT_R64G64B64_SFLOAT,"192-bit",24,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SFLOAT, -1), new Component('G', 64, NumericFormat.SFLOAT, -1), new Component('B', 64, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16,"10-bit 3-plane 444",6,1,1,1,16,"","444",new Component[] {new Component('G', 10, NumericFormat.UNORM, 0), new Component('B', 10, NumericFormat.UNORM, 1), new Component('R', 10, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(1, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(2, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16")},null),
	VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK,"ASTC_12x10",16,12,10,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK,"ASTC_5x4",16,5,4,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R64G64_SFLOAT(VK14.VkFormat.VK_FORMAT_R64G64_SFLOAT,"128-bit",16,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SFLOAT, -1), new Component('G', 64, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_G16_B16R16_2PLANE_422_UNORM(VK14.VkFormat.VK_FORMAT_G16_B16R16_2PLANE_422_UNORM,"16-bit 2-plane 422",6,1,1,1,0,"","422",new Component[] {new Component('G', 16, NumericFormat.UNORM, 0), new Component('B', 16, NumericFormat.UNORM, 1), new Component('R', 16, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(1, 2, 1, "VK_FORMAT_R16G16_UNORM")},null),
	VK_FORMAT_B10G11R11_UFLOAT_PACK32(VK14.VkFormat.VK_FORMAT_B10G11R11_UFLOAT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('B', 10, NumericFormat.UFLOAT, -1), new Component('G', 11, NumericFormat.UFLOAT, -1), new Component('R', 11, NumericFormat.UFLOAT, -1)},null,new String[] {"R11fG11fB10f"}),
	VK_FORMAT_R8G8B8_SSCALED(VK14.VkFormat.VK_FORMAT_R8G8B8_SSCALED,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SSCALED, -1), new Component('G', 8, NumericFormat.SSCALED, -1), new Component('B', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_BC3_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_BC3_SRGB_BLOCK,"BC3",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK,"ASTC_8x5",16,8,5,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R8G8_UNORM(VK14.VkFormat.VK_FORMAT_R8G8_UNORM,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1)},null,new String[] {"Rg8"}),
	VK_FORMAT_BC1_RGBA_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC1_RGBA_UNORM_BLOCK,"BC1_RGBA",8,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK,"ETC2_RGB",8,4,4,1,0,"ETC2","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM(VK14.VkFormat.VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM,"8-bit 3-plane 444",3,1,1,1,0,"","444",new Component[] {new Component('G', 8, NumericFormat.UNORM, 0), new Component('B', 8, NumericFormat.UNORM, 1), new Component('R', 8, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(1, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(2, 1, 1, "VK_FORMAT_R8_UNORM")},null),
	VK_FORMAT_G16B16G16R16_422_UNORM(VK14.VkFormat.VK_FORMAT_G16B16G16R16_422_UNORM,"64-bit G16B16G16R16",8,2,1,1,0,"","422",new Component[] {new Component('G', 16, NumericFormat.UNORM, -1), new Component('B', 16, NumericFormat.UNORM, -1), new Component('G', 16, NumericFormat.UNORM, -1), new Component('R', 16, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16,"10-bit 3-plane 422",6,1,1,1,16,"","422",new Component[] {new Component('G', 10, NumericFormat.UNORM, 0), new Component('B', 10, NumericFormat.UNORM, 1), new Component('R', 10, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(1, 2, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(2, 2, 1, "VK_FORMAT_R10X6_UNORM_PACK16")},null),
	VK_FORMAT_B5G6R5_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_B5G6R5_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('B', 5, NumericFormat.UNORM, -1), new Component('G', 6, NumericFormat.UNORM, -1), new Component('R', 5, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_5x4_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_5x4_UNORM_BLOCK,"ASTC_5x4",16,5,4,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R32G32_SFLOAT(VK14.VkFormat.VK_FORMAT_R32G32_SFLOAT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SFLOAT, -1), new Component('G', 32, NumericFormat.SFLOAT, -1)},null,new String[] {"Rg32f"}),
	VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK,"ETC2_RGBA",8,4,4,1,0,"ETC2","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK,"ETC2_EAC_RGBA",16,4,4,1,0,"ETC2","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_5x4_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_5x4_SRGB_BLOCK,"ASTC_5x4",16,5,4,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16_SINT(VK14.VkFormat.VK_FORMAT_R16_SINT,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SINT, -1)},null,new String[] {"R16i"}),
	VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK,"ETC2_RGB",8,4,4,1,0,"ETC2","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A8B8G8R8_SSCALED_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_SSCALED_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.SSCALED, -1), new Component('B', 8, NumericFormat.SSCALED, -1), new Component('G', 8, NumericFormat.SSCALED, -1), new Component('R', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_S8_UINT(VK14.VkFormat.VK_FORMAT_S8_UINT,"S8",1,1,1,1,0,"","",new Component[] {new Component('S', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16,"10-bit 3-plane 420",6,1,1,1,16,"","420",new Component[] {new Component('G', 10, NumericFormat.UNORM, 0), new Component('B', 10, NumericFormat.UNORM, 1), new Component('R', 10, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(1, 2, 2, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(2, 2, 2, "VK_FORMAT_R10X6_UNORM_PACK16")},null),
	VK_FORMAT_ASTC_4x4_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_4x4_SRGB_BLOCK,"ASTC_4x4",16,4,4,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G8_B8R8_2PLANE_444_UNORM(VK14.VkFormat.VK_FORMAT_G8_B8R8_2PLANE_444_UNORM,"8-bit 2-plane 444",3,1,1,1,0,"","444",new Component[] {new Component('G', 8, NumericFormat.UNORM, 0), new Component('B', 8, NumericFormat.UNORM, 1), new Component('R', 8, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(1, 1, 1, "VK_FORMAT_R8G8_UNORM")},null),
	VK_FORMAT_R16_UNORM(VK14.VkFormat.VK_FORMAT_R16_UNORM,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UNORM, -1)},null,new String[] {"R16"}),
	VK_FORMAT_D16_UNORM_S8_UINT(VK14.VkFormat.VK_FORMAT_D16_UNORM_S8_UINT,"D16S8",3,1,1,1,0,"","",new Component[] {new Component('D', 16, NumericFormat.UNORM, -1), new Component('S', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_G8B8G8R8_422_UNORM(VK14.VkFormat.VK_FORMAT_G8B8G8R8_422_UNORM,"32-bit G8B8G8R8",4,2,1,1,0,"","422",new Component[] {new Component('G', 8, NumericFormat.UNORM, -1), new Component('B', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('R', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R64_SINT(VK14.VkFormat.VK_FORMAT_R64_SINT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SINT, -1)},null,new String[] {"R64i"}),
	VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK,"ETC2_RGBA",8,4,4,1,0,"ETC2","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_B8G8R8A8_UINT(VK14.VkFormat.VK_FORMAT_B8G8R8A8_UINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.UINT, -1), new Component('G', 8, NumericFormat.UINT, -1), new Component('R', 8, NumericFormat.UINT, -1), new Component('A', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_ASTC_10x8_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x8_UNORM_BLOCK,"ASTC_10x8",16,10,8,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A4B4G4R4_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_A4B4G4R4_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('A', 4, NumericFormat.UNORM, -1), new Component('B', 4, NumericFormat.UNORM, -1), new Component('G', 4, NumericFormat.UNORM, -1), new Component('R', 4, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16G16B16A16_SSCALED(VK14.VkFormat.VK_FORMAT_R16G16B16A16_SSCALED,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SSCALED, -1), new Component('G', 16, NumericFormat.SSCALED, -1), new Component('B', 16, NumericFormat.SSCALED, -1), new Component('A', 16, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_R8G8B8A8_UINT(VK14.VkFormat.VK_FORMAT_R8G8B8A8_UINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UINT, -1), new Component('G', 8, NumericFormat.UINT, -1), new Component('B', 8, NumericFormat.UINT, -1), new Component('A', 8, NumericFormat.UINT, -1)},null,new String[] {"Rgba8ui"}),
	VK_FORMAT_ASTC_12x10_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_12x10_UNORM_BLOCK,"ASTC_12x10",16,12,10,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM(VK14.VkFormat.VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM,"8-bit 3-plane 422",3,1,1,1,0,"","422",new Component[] {new Component('G', 8, NumericFormat.UNORM, 0), new Component('B', 8, NumericFormat.UNORM, 1), new Component('R', 8, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(1, 2, 1, "VK_FORMAT_R8_UNORM"), new Plane(2, 2, 1, "VK_FORMAT_R8_UNORM")},null),
	VK_FORMAT_ASTC_10x6_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x6_UNORM_BLOCK,"ASTC_10x6",16,10,6,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_12x12_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_12x12_UNORM_BLOCK,"ASTC_12x12",16,12,12,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R8G8B8_UINT(VK14.VkFormat.VK_FORMAT_R8G8B8_UINT,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UINT, -1), new Component('G', 8, NumericFormat.UINT, -1), new Component('B', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK,"ASTC_8x6",16,8,6,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_G8_B8R8_2PLANE_420_UNORM(VK14.VkFormat.VK_FORMAT_G8_B8R8_2PLANE_420_UNORM,"8-bit 2-plane 420",3,1,1,1,0,"","420",new Component[] {new Component('G', 8, NumericFormat.UNORM, 0), new Component('B', 8, NumericFormat.UNORM, 1), new Component('R', 8, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(1, 2, 2, "VK_FORMAT_R8G8_UNORM")},null),
	VK_FORMAT_R12X4_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_R12X4_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('R', 12, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_B8G8R8_UINT(VK14.VkFormat.VK_FORMAT_B8G8R8_UINT,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.UINT, -1), new Component('G', 8, NumericFormat.UINT, -1), new Component('R', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_R8G8_SSCALED(VK14.VkFormat.VK_FORMAT_R8G8_SSCALED,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SSCALED, -1), new Component('G', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_G16_B16R16_2PLANE_444_UNORM(VK14.VkFormat.VK_FORMAT_G16_B16R16_2PLANE_444_UNORM,"16-bit 2-plane 444",6,1,1,1,0,"","444",new Component[] {new Component('G', 16, NumericFormat.UNORM, 0), new Component('B', 16, NumericFormat.UNORM, 1), new Component('R', 16, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(1, 1, 1, "VK_FORMAT_R16G16_UNORM")},null),
	VK_FORMAT_R32G32B32A32_SINT(VK14.VkFormat.VK_FORMAT_R32G32B32A32_SINT,"128-bit",16,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SINT, -1), new Component('G', 32, NumericFormat.SINT, -1), new Component('B', 32, NumericFormat.SINT, -1), new Component('A', 32, NumericFormat.SINT, -1)},null,new String[] {"Rgba32i"}),
	VK_FORMAT_R16G16_SINT(VK14.VkFormat.VK_FORMAT_R16G16_SINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SINT, -1), new Component('G', 16, NumericFormat.SINT, -1)},null,new String[] {"Rg16i"}),
	VK_FORMAT_A2B10G10R10_SINT_PACK32(VK14.VkFormat.VK_FORMAT_A2B10G10R10_SINT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.SINT, -1), new Component('B', 10, NumericFormat.SINT, -1), new Component('G', 10, NumericFormat.SINT, -1), new Component('R', 10, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_R16G16B16_SFLOAT(VK14.VkFormat.VK_FORMAT_R16G16B16_SFLOAT,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SFLOAT, -1), new Component('G', 16, NumericFormat.SFLOAT, -1), new Component('B', 16, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R64G64B64A64_SFLOAT(VK14.VkFormat.VK_FORMAT_R64G64B64A64_SFLOAT,"256-bit",32,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SFLOAT, -1), new Component('G', 64, NumericFormat.SFLOAT, -1), new Component('B', 64, NumericFormat.SFLOAT, -1), new Component('A', 64, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R8_SSCALED(VK14.VkFormat.VK_FORMAT_R8_SSCALED,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_A2R10G10B10_USCALED_PACK32(VK14.VkFormat.VK_FORMAT_A2R10G10B10_USCALED_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.USCALED, -1), new Component('R', 10, NumericFormat.USCALED, -1), new Component('G', 10, NumericFormat.USCALED, -1), new Component('B', 10, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_B5G5R5A1_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_B5G5R5A1_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('B', 5, NumericFormat.UNORM, -1), new Component('G', 5, NumericFormat.UNORM, -1), new Component('R', 5, NumericFormat.UNORM, -1), new Component('A', 1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC1_RGB_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_BC1_RGB_SRGB_BLOCK,"BC1_RGB",8,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_R16G16B16_SSCALED(VK14.VkFormat.VK_FORMAT_R16G16B16_SSCALED,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SSCALED, -1), new Component('G', 16, NumericFormat.SSCALED, -1), new Component('B', 16, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_G16_B16R16_2PLANE_420_UNORM(VK14.VkFormat.VK_FORMAT_G16_B16R16_2PLANE_420_UNORM,"16-bit 2-plane 420",6,1,1,1,0,"","420",new Component[] {new Component('G', 16, NumericFormat.UNORM, 0), new Component('B', 16, NumericFormat.UNORM, 1), new Component('R', 16, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(1, 2, 2, "VK_FORMAT_R16G16_UNORM")},null),
	VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK,"ASTC_5x5",16,5,5,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_BC6H_UFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_BC6H_UFLOAT_BLOCK,"BC6H",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UFLOAT, -1), new Component('G', -1, NumericFormat.UFLOAT, -1), new Component('B', -1, NumericFormat.UFLOAT, -1)},null,null),
	VK_FORMAT_A2R10G10B10_SINT_PACK32(VK14.VkFormat.VK_FORMAT_A2R10G10B10_SINT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.SINT, -1), new Component('R', 10, NumericFormat.SINT, -1), new Component('G', 10, NumericFormat.SINT, -1), new Component('B', 10, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_R16G16B16_UNORM(VK14.VkFormat.VK_FORMAT_R16G16B16_UNORM,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UNORM, -1), new Component('G', 16, NumericFormat.UNORM, -1), new Component('B', 16, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R10X6_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_R10X6_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('R', 10, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A2B10G10R10_SSCALED_PACK32(VK14.VkFormat.VK_FORMAT_A2B10G10R10_SSCALED_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.SSCALED, -1), new Component('B', 10, NumericFormat.SSCALED, -1), new Component('G', 10, NumericFormat.SSCALED, -1), new Component('R', 10, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_BC5_SNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC5_SNORM_BLOCK,"BC5",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SNORM, -1), new Component('G', -1, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_B8G8R8A8_UNORM(VK14.VkFormat.VK_FORMAT_B8G8R8A8_UNORM,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('R', 8, NumericFormat.UNORM, -1), new Component('A', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_4x4_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_4x4_UNORM_BLOCK,"ASTC_4x4",16,4,4,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_E5B9G9R9_UFLOAT_PACK32(VK14.VkFormat.VK_FORMAT_E5B9G9R9_UFLOAT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('B', 9, NumericFormat.UFLOAT, -1), new Component('G', 9, NumericFormat.UFLOAT, -1), new Component('R', 9, NumericFormat.UFLOAT, -1)},null,null),
	VK_FORMAT_D16_UNORM(VK14.VkFormat.VK_FORMAT_D16_UNORM,"D16",2,1,1,1,0,"","",new Component[] {new Component('D', 16, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16,"12-bit 2-plane 422",6,1,1,1,16,"","422",new Component[] {new Component('G', 12, NumericFormat.UNORM, 0), new Component('B', 12, NumericFormat.UNORM, 1), new Component('R', 12, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(1, 2, 1, "VK_FORMAT_R12X4G12X4_UNORM_2PACK16")},null),
	VK_FORMAT_A2B10G10R10_UINT_PACK32(VK14.VkFormat.VK_FORMAT_A2B10G10R10_UINT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.UINT, -1), new Component('B', 10, NumericFormat.UINT, -1), new Component('G', 10, NumericFormat.UINT, -1), new Component('R', 10, NumericFormat.UINT, -1)},null,new String[] {"Rgb10a2ui"}),
	VK_FORMAT_BC1_RGB_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC1_RGB_UNORM_BLOCK,"BC1_RGB",8,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R64G64B64_UINT(VK14.VkFormat.VK_FORMAT_R64G64B64_UINT,"192-bit",24,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.UINT, -1), new Component('G', 64, NumericFormat.UINT, -1), new Component('B', 64, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_D24_UNORM_S8_UINT(VK14.VkFormat.VK_FORMAT_D24_UNORM_S8_UINT,"D24S8",4,1,1,1,0,"","",new Component[] {new Component('D', 24, NumericFormat.UNORM, -1), new Component('S', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK,"ASTC_10x10",16,10,10,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_B8G8R8_UNORM(VK14.VkFormat.VK_FORMAT_B8G8R8_UNORM,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('R', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16(VK14.VkFormat.VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16,"64-bit B12G12R12G12",8,2,1,1,16,"","422",new Component[] {new Component('B', 12, NumericFormat.UNORM, -1), new Component('G', 12, NumericFormat.UNORM, -1), new Component('R', 12, NumericFormat.UNORM, -1), new Component('G', 12, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_5x5_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_5x5_SRGB_BLOCK,"ASTC_5x5",16,5,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G8_B8R8_2PLANE_422_UNORM(VK14.VkFormat.VK_FORMAT_G8_B8R8_2PLANE_422_UNORM,"8-bit 2-plane 422",3,1,1,1,0,"","422",new Component[] {new Component('G', 8, NumericFormat.UNORM, 0), new Component('B', 8, NumericFormat.UNORM, 1), new Component('R', 8, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R8_UNORM"), new Plane(1, 2, 1, "VK_FORMAT_R8G8_UNORM")},null),
	VK_FORMAT_R8G8B8A8_SRGB(VK14.VkFormat.VK_FORMAT_R8G8B8A8_SRGB,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SRGB, -1), new Component('G', 8, NumericFormat.SRGB, -1), new Component('B', 8, NumericFormat.SRGB, -1), new Component('A', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R8G8B8A8_UNORM(VK14.VkFormat.VK_FORMAT_R8G8B8A8_UNORM,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('B', 8, NumericFormat.UNORM, -1), new Component('A', 8, NumericFormat.UNORM, -1)},null,new String[] {"Rgba8"}),
	VK_FORMAT_A1B5G5R5_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_A1B5G5R5_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('A', 1, NumericFormat.UNORM, -1), new Component('B', 5, NumericFormat.UNORM, -1), new Component('G', 5, NumericFormat.UNORM, -1), new Component('R', 5, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R8_USCALED(VK14.VkFormat.VK_FORMAT_R8_USCALED,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R8G8_SRGB(VK14.VkFormat.VK_FORMAT_R8G8_SRGB,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SRGB, -1), new Component('G', 8, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_R8G8B8_SRGB(VK14.VkFormat.VK_FORMAT_R8G8B8_SRGB,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SRGB, -1), new Component('G', 8, NumericFormat.SRGB, -1), new Component('B', 8, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16,"10-bit 2-plane 420",6,1,1,1,16,"","420",new Component[] {new Component('G', 10, NumericFormat.UNORM, 0), new Component('B', 10, NumericFormat.UNORM, 1), new Component('R', 10, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(1, 2, 2, "VK_FORMAT_R10X6G10X6_UNORM_2PACK16")},null),
	VK_FORMAT_B8G8R8_SRGB(VK14.VkFormat.VK_FORMAT_B8G8R8_SRGB,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SRGB, -1), new Component('G', 8, NumericFormat.SRGB, -1), new Component('R', 8, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_A2R10G10B10_UINT_PACK32(VK14.VkFormat.VK_FORMAT_A2R10G10B10_UINT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.UINT, -1), new Component('R', 10, NumericFormat.UINT, -1), new Component('G', 10, NumericFormat.UINT, -1), new Component('B', 10, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_EAC_R11G11_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_EAC_R11G11_UNORM_BLOCK,"EAC_RG",16,4,4,1,0,"EAC","",new Component[] {new Component('R', 11, NumericFormat.UNORM, -1), new Component('G', 11, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_10x5_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x5_SRGB_BLOCK,"ASTC_10x5",16,10,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R8G8B8_SNORM(VK14.VkFormat.VK_FORMAT_R8G8B8_SNORM,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SNORM, -1), new Component('G', 8, NumericFormat.SNORM, -1), new Component('B', 8, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_R16G16B16_USCALED(VK14.VkFormat.VK_FORMAT_R16G16B16_USCALED,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.USCALED, -1), new Component('G', 16, NumericFormat.USCALED, -1), new Component('B', 16, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R32G32B32_UINT(VK14.VkFormat.VK_FORMAT_R32G32B32_UINT,"96-bit",12,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.UINT, -1), new Component('G', 32, NumericFormat.UINT, -1), new Component('B', 32, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_R10X6G10X6_UNORM_2PACK16(VK14.VkFormat.VK_FORMAT_R10X6G10X6_UNORM_2PACK16,"32-bit",4,1,1,1,16,"","",new Component[] {new Component('R', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16(VK14.VkFormat.VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16,"64-bit G10B10G10R10",8,2,1,1,16,"","422",new Component[] {new Component('G', 10, NumericFormat.UNORM, -1), new Component('B', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1), new Component('R', 10, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK,"ASTC_12x12",16,12,12,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R32G32_UINT(VK14.VkFormat.VK_FORMAT_R32G32_UINT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.UINT, -1), new Component('G', 32, NumericFormat.UINT, -1)},null,new String[] {"Rg32ui"}),
	VK_FORMAT_R8G8_UINT(VK14.VkFormat.VK_FORMAT_R8G8_UINT,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UINT, -1), new Component('G', 8, NumericFormat.UINT, -1)},null,new String[] {"Rg8ui"}),
	VK_FORMAT_R8_UNORM(VK14.VkFormat.VK_FORMAT_R8_UNORM,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.UNORM, -1)},null,new String[] {"R8"}),
	VK_FORMAT_BC7_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_BC7_SRGB_BLOCK,"BC7",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_B4G4R4A4_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_B4G4R4A4_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('B', 4, NumericFormat.UNORM, -1), new Component('G', 4, NumericFormat.UNORM, -1), new Component('R', 4, NumericFormat.UNORM, -1), new Component('A', 4, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC2_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_BC2_SRGB_BLOCK,"BC2",16,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_6x5_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_6x5_SRGB_BLOCK,"ASTC_6x5",16,6,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16_USCALED(VK14.VkFormat.VK_FORMAT_R16_USCALED,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R32_SFLOAT(VK14.VkFormat.VK_FORMAT_R32_SFLOAT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SFLOAT, -1)},null,new String[] {"R32f"}),
	VK_FORMAT_B8G8R8A8_SRGB(VK14.VkFormat.VK_FORMAT_B8G8R8A8_SRGB,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SRGB, -1), new Component('G', 8, NumericFormat.SRGB, -1), new Component('R', 8, NumericFormat.SRGB, -1), new Component('A', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16,"10-bit 2-plane 444",6,1,1,1,16,"","444",new Component[] {new Component('G', 10, NumericFormat.UNORM, 0), new Component('B', 10, NumericFormat.UNORM, 1), new Component('R', 10, NumericFormat.UNORM, 1)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R10X6_UNORM_PACK16"), new Plane(1, 1, 1, "VK_FORMAT_R10X6G10X6_UNORM_2PACK16")},null),
	VK_FORMAT_ASTC_10x10_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x10_SRGB_BLOCK,"ASTC_10x10",16,10,10,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R32G32B32A32_SFLOAT(VK14.VkFormat.VK_FORMAT_R32G32B32A32_SFLOAT,"128-bit",16,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SFLOAT, -1), new Component('G', 32, NumericFormat.SFLOAT, -1), new Component('B', 32, NumericFormat.SFLOAT, -1), new Component('A', 32, NumericFormat.SFLOAT, -1)},null,new String[] {"Rgba32f"}),
	VK_FORMAT_EAC_R11G11_SNORM_BLOCK(VK14.VkFormat.VK_FORMAT_EAC_R11G11_SNORM_BLOCK,"EAC_RG",16,4,4,1,0,"EAC","",new Component[] {new Component('R', 11, NumericFormat.SNORM, -1), new Component('G', 11, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_R64G64_SINT(VK14.VkFormat.VK_FORMAT_R64G64_SINT,"128-bit",16,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SINT, -1), new Component('G', 64, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_R16_UINT(VK14.VkFormat.VK_FORMAT_R16_UINT,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UINT, -1)},null,new String[] {"R16ui"}),
	VK_FORMAT_A2R10G10B10_UNORM_PACK32(VK14.VkFormat.VK_FORMAT_A2R10G10B10_UNORM_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.UNORM, -1), new Component('R', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1), new Component('B', 10, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R8G8_SNORM(VK14.VkFormat.VK_FORMAT_R8G8_SNORM,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SNORM, -1), new Component('G', 8, NumericFormat.SNORM, -1)},null,new String[] {"Rg8Snorm"}),
	VK_FORMAT_R64G64B64A64_SINT(VK14.VkFormat.VK_FORMAT_R64G64B64A64_SINT,"256-bit",32,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SINT, -1), new Component('G', 64, NumericFormat.SINT, -1), new Component('B', 64, NumericFormat.SINT, -1), new Component('A', 64, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_ASTC_8x8_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x8_UNORM_BLOCK,"ASTC_8x8",16,8,8,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A8B8G8R8_UNORM_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_UNORM_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.UNORM, -1), new Component('B', 8, NumericFormat.UNORM, -1), new Component('G', 8, NumericFormat.UNORM, -1), new Component('R', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC1_RGBA_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_BC1_RGBA_SRGB_BLOCK,"BC1_RGBA",8,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_8x5_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x5_UNORM_BLOCK,"ASTC_8x5",16,8,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_8x6_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x6_UNORM_BLOCK,"ASTC_8x6",16,8,6,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_8x8_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x8_SRGB_BLOCK,"ASTC_8x8",16,8,8,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R64_UINT(VK14.VkFormat.VK_FORMAT_R64_UINT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.UINT, -1)},null,new String[] {"R64ui"}),
	VK_FORMAT_R32G32_SINT(VK14.VkFormat.VK_FORMAT_R32G32_SINT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SINT, -1), new Component('G', 32, NumericFormat.SINT, -1)},null,new String[] {"Rg32i"}),
	VK_FORMAT_R5G6B5_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_R5G6B5_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('R', 5, NumericFormat.UNORM, -1), new Component('G', 6, NumericFormat.UNORM, -1), new Component('B', 5, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK,"ETC2_EAC_RGBA",16,4,4,1,0,"ETC2","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16,"12-bit 3-plane 422",6,1,1,1,16,"","422",new Component[] {new Component('G', 12, NumericFormat.UNORM, 0), new Component('B', 12, NumericFormat.UNORM, 1), new Component('R', 12, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(1, 2, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(2, 2, 1, "VK_FORMAT_R12X4_UNORM_PACK16")},null),
	VK_FORMAT_A4R4G4B4_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_A4R4G4B4_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('A', 4, NumericFormat.UNORM, -1), new Component('R', 4, NumericFormat.UNORM, -1), new Component('G', 4, NumericFormat.UNORM, -1), new Component('B', 4, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_6x6_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_6x6_SRGB_BLOCK,"ASTC_6x6",16,6,6,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16G16_SNORM(VK14.VkFormat.VK_FORMAT_R16G16_SNORM,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SNORM, -1), new Component('G', 16, NumericFormat.SNORM, -1)},null,new String[] {"Rg16Snorm"}),
	VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK,"ASTC_4x4",16,4,4,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16(VK14.VkFormat.VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16,"64-bit R10G10B10A10",8,1,1,1,16,"","444",new Component[] {new Component('R', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1), new Component('B', 10, NumericFormat.UNORM, -1), new Component('A', 10, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_R16G16_UINT(VK14.VkFormat.VK_FORMAT_R16G16_UINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UINT, -1), new Component('G', 16, NumericFormat.UINT, -1)},null,new String[] {"Rg16ui"}),
	VK_FORMAT_A8B8G8R8_SRGB_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_SRGB_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.UNORM, -1), new Component('B', 8, NumericFormat.SRGB, -1), new Component('G', 8, NumericFormat.SRGB, -1), new Component('R', 8, NumericFormat.SRGB, -1)},null,null),
	VK_FORMAT_R16_SNORM(VK14.VkFormat.VK_FORMAT_R16_SNORM,"16-bit",2,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SNORM, -1)},null,new String[] {"R16Snorm"}),
	VK_FORMAT_R64_SFLOAT(VK14.VkFormat.VK_FORMAT_R64_SFLOAT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 64, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_ASTC_10x6_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x6_SRGB_BLOCK,"ASTC_10x6",16,10,6,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_D32_SFLOAT_S8_UINT(VK14.VkFormat.VK_FORMAT_D32_SFLOAT_S8_UINT,"D32S8",5,1,1,1,0,"","",new Component[] {new Component('D', 32, NumericFormat.SFLOAT, -1), new Component('S', 8, NumericFormat.UINT, -1)},null,null),
	VK_FORMAT_ASTC_5x5_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_5x5_UNORM_BLOCK,"ASTC_5x5",16,5,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM(VK14.VkFormat.VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM,"16-bit 3-plane 422",6,1,1,1,0,"","422",new Component[] {new Component('G', 16, NumericFormat.UNORM, 0), new Component('B', 16, NumericFormat.UNORM, 1), new Component('R', 16, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(1, 2, 1, "VK_FORMAT_R16_UNORM"), new Plane(2, 2, 1, "VK_FORMAT_R16_UNORM")},null),
	VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM(VK14.VkFormat.VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM,"16-bit 3-plane 420",6,1,1,1,0,"","420",new Component[] {new Component('G', 16, NumericFormat.UNORM, 0), new Component('B', 16, NumericFormat.UNORM, 1), new Component('R', 16, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(1, 2, 2, "VK_FORMAT_R16_UNORM"), new Plane(2, 2, 2, "VK_FORMAT_R16_UNORM")},null),
	VK_FORMAT_R32_SINT(VK14.VkFormat.VK_FORMAT_R32_SINT,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 32, NumericFormat.SINT, -1)},null,new String[] {"R32i"}),
	VK_FORMAT_A2B10G10R10_UNORM_PACK32(VK14.VkFormat.VK_FORMAT_A2B10G10R10_UNORM_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.UNORM, -1), new Component('B', 10, NumericFormat.UNORM, -1), new Component('G', 10, NumericFormat.UNORM, -1), new Component('R', 10, NumericFormat.UNORM, -1)},null,new String[] {"Rgb10A2"}),
	VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK,"ASTC_8x8",16,8,8,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R16G16_SSCALED(VK14.VkFormat.VK_FORMAT_R16G16_SSCALED,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SSCALED, -1), new Component('G', 16, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_B8G8R8_USCALED(VK14.VkFormat.VK_FORMAT_B8G8R8_USCALED,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.USCALED, -1), new Component('G', 8, NumericFormat.USCALED, -1), new Component('R', 8, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R8_SINT(VK14.VkFormat.VK_FORMAT_R8_SINT,"8-bit",1,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SINT, -1)},null,new String[] {"R8i"}),
	VK_FORMAT_B8G8R8_SSCALED(VK14.VkFormat.VK_FORMAT_B8G8R8_SSCALED,"24-bit",3,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SSCALED, -1), new Component('G', 8, NumericFormat.SSCALED, -1), new Component('R', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_ASTC_10x5_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x5_UNORM_BLOCK,"ASTC_10x5",16,10,5,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.UNORM, -1), new Component('G', -1, NumericFormat.UNORM, -1), new Component('B', -1, NumericFormat.UNORM, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16(VK14.VkFormat.VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16,"12-bit 3-plane 420",6,1,1,1,16,"","420",new Component[] {new Component('G', 12, NumericFormat.UNORM, 0), new Component('B', 12, NumericFormat.UNORM, 1), new Component('R', 12, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(1, 2, 2, "VK_FORMAT_R12X4_UNORM_PACK16"), new Plane(2, 2, 2, "VK_FORMAT_R12X4_UNORM_PACK16")},null),
	VK_FORMAT_ASTC_12x12_SRGB_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_12x12_SRGB_BLOCK,"ASTC_12x12",16,12,12,1,0,"ASTC LDR","",new Component[] {new Component('R', -1, NumericFormat.SRGB, -1), new Component('G', -1, NumericFormat.SRGB, -1), new Component('B', -1, NumericFormat.SRGB, -1), new Component('A', -1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_EAC_R11_UNORM_BLOCK(VK14.VkFormat.VK_FORMAT_EAC_R11_UNORM_BLOCK,"EAC_R",8,4,4,1,0,"EAC","",new Component[] {new Component('R', 11, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_A2B10G10R10_SNORM_PACK32(VK14.VkFormat.VK_FORMAT_A2B10G10R10_SNORM_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.SNORM, -1), new Component('B', 10, NumericFormat.SNORM, -1), new Component('G', 10, NumericFormat.SNORM, -1), new Component('R', 10, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_R4G4_UNORM_PACK8(VK14.VkFormat.VK_FORMAT_R4G4_UNORM_PACK8,"8-bit",1,1,1,1,8,"","",new Component[] {new Component('R', 4, NumericFormat.UNORM, -1), new Component('G', 4, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_B8G8R8A8_SSCALED(VK14.VkFormat.VK_FORMAT_B8G8R8A8_SSCALED,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SSCALED, -1), new Component('G', 8, NumericFormat.SSCALED, -1), new Component('R', 8, NumericFormat.SSCALED, -1), new Component('A', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_R8G8B8A8_SSCALED(VK14.VkFormat.VK_FORMAT_R8G8B8A8_SSCALED,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('R', 8, NumericFormat.SSCALED, -1), new Component('G', 8, NumericFormat.SSCALED, -1), new Component('B', 8, NumericFormat.SSCALED, -1), new Component('A', 8, NumericFormat.SSCALED, -1)},null,null),
	VK_FORMAT_R16G16B16A16_UNORM(VK14.VkFormat.VK_FORMAT_R16G16B16A16_UNORM,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.UNORM, -1), new Component('G', 16, NumericFormat.UNORM, -1), new Component('B', 16, NumericFormat.UNORM, -1), new Component('A', 16, NumericFormat.UNORM, -1)},null,new String[] {"Rgba16"}),
	VK_FORMAT_B8G8R8A8_SNORM(VK14.VkFormat.VK_FORMAT_B8G8R8A8_SNORM,"32-bit",4,1,1,1,0,"","",new Component[] {new Component('B', 8, NumericFormat.SNORM, -1), new Component('G', 8, NumericFormat.SNORM, -1), new Component('R', 8, NumericFormat.SNORM, -1), new Component('A', 8, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_A8_UNORM(VK14.VkFormat.VK_FORMAT_A8_UNORM,"8-bit alpha",1,1,1,1,0,"","",new Component[] {new Component('A', 8, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK,"ASTC_6x6",16,6,6,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_R16G16B16A16_SINT(VK14.VkFormat.VK_FORMAT_R16G16B16A16_SINT,"64-bit",8,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SINT, -1), new Component('G', 16, NumericFormat.SINT, -1), new Component('B', 16, NumericFormat.SINT, -1), new Component('A', 16, NumericFormat.SINT, -1)},null,new String[] {"Rgba16i"}),
	VK_FORMAT_R16G16B16_SNORM(VK14.VkFormat.VK_FORMAT_R16G16B16_SNORM,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SNORM, -1), new Component('G', 16, NumericFormat.SNORM, -1), new Component('B', 16, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_A8B8G8R8_SINT_PACK32(VK14.VkFormat.VK_FORMAT_A8B8G8R8_SINT_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 8, NumericFormat.SINT, -1), new Component('B', 8, NumericFormat.SINT, -1), new Component('G', 8, NumericFormat.SINT, -1), new Component('R', 8, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_R5G5B5A1_UNORM_PACK16(VK14.VkFormat.VK_FORMAT_R5G5B5A1_UNORM_PACK16,"16-bit",2,1,1,1,16,"","",new Component[] {new Component('R', 5, NumericFormat.UNORM, -1), new Component('G', 5, NumericFormat.UNORM, -1), new Component('B', 5, NumericFormat.UNORM, -1), new Component('A', 1, NumericFormat.UNORM, -1)},null,null),
	VK_FORMAT_BC4_SNORM_BLOCK(VK14.VkFormat.VK_FORMAT_BC4_SNORM_BLOCK,"BC4",8,4,4,1,0,"BC","",new Component[] {new Component('R', -1, NumericFormat.SNORM, -1)},null,null),
	VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM(VK14.VkFormat.VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM,"16-bit 3-plane 444",6,1,1,1,0,"","444",new Component[] {new Component('G', 16, NumericFormat.UNORM, 0), new Component('B', 16, NumericFormat.UNORM, 1), new Component('R', 16, NumericFormat.UNORM, 2)},new Plane[] {new Plane(0, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(1, 1, 1, "VK_FORMAT_R16_UNORM"), new Plane(2, 1, 1, "VK_FORMAT_R16_UNORM")},null),
	VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK(VK14.VkFormat.VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK,"ASTC_10x5",16,10,5,1,0,"ASTC HDR","",new Component[] {new Component('R', -1, NumericFormat.SFLOAT, -1), new Component('G', -1, NumericFormat.SFLOAT, -1), new Component('B', -1, NumericFormat.SFLOAT, -1), new Component('A', -1, NumericFormat.SFLOAT, -1)},null,null),
	VK_FORMAT_A2B10G10R10_USCALED_PACK32(VK14.VkFormat.VK_FORMAT_A2B10G10R10_USCALED_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.USCALED, -1), new Component('B', 10, NumericFormat.USCALED, -1), new Component('G', 10, NumericFormat.USCALED, -1), new Component('R', 10, NumericFormat.USCALED, -1)},null,null),
	VK_FORMAT_R16G16B16_SINT(VK14.VkFormat.VK_FORMAT_R16G16B16_SINT,"48-bit",6,1,1,1,0,"","",new Component[] {new Component('R', 16, NumericFormat.SINT, -1), new Component('G', 16, NumericFormat.SINT, -1), new Component('B', 16, NumericFormat.SINT, -1)},null,null),
	VK_FORMAT_A2R10G10B10_SSCALED_PACK32(VK14.VkFormat.VK_FORMAT_A2R10G10B10_SSCALED_PACK32,"32-bit",4,1,1,1,32,"","",new Component[] {new Component('A', 2, NumericFormat.SSCALED, -1), new Component('R', 10, NumericFormat.SSCALED, -1), new Component('G', 10, NumericFormat.SSCALED, -1), new Component('B', 10, NumericFormat.SSCALED, -1)},null,null);
	public final int value;

	public final String clazz;

	public final int blockSize;

	public final int blockExtentX;

	public final int blockExtentY;

	public final int blockExtentZ;

	public final int packed;

	public final String compressed;

	public final String chroma;

	public final Component[] components;

	public final Plane[] planes;

	public final String[] spirVImageFormats;

	Formats(int value, String clazz, int blockSize, int blockExtentX, int blockExtentY, int blockExtentZ, int packed, String compressed, String chroma, Component[] components, Plane[] planes, String[] spirVImageFormats) {
		this.value = value;
		this.clazz = clazz;
		this.blockSize = blockSize;
		this.blockExtentX = blockExtentX;
		this.blockExtentY = blockExtentY;
		this.blockExtentZ = blockExtentZ;
		this.packed = packed;
		this.compressed = compressed;
		this.chroma = chroma;
		this.components = components;
		this.planes = planes;
		this.spirVImageFormats = spirVImageFormats;
	}
	public enum NumericFormat{
		BOOL(),
		SFIXED5(),
		SFLOAT(),
		SINT(),
		SNORM(),
		SRGB(),
		SSCALED(),
		UFLOAT(),
		UINT(),
		UNORM(),
		USCALED();
		NumericFormat() {
		}
	}

	public record Component(char name, int bits, NumericFormat numericFormat, int planeIndex){
	}

	public record Plane(int index, int widthDivisor, int heightDivisor, String compatible){
	}

}
