# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/KLVulkan # location for the settings.xml file

    - name: KLVulkan Build with Maven
      run: mvn -B package --file "${{ github.workspace }}/KLVulkan/pom.xml"
    - name: KLVulkan Test
      run: ls -l "${{ github.workspace }}/KLVulkan/"
    - name: KLVulkan Test2
      run: ls -l "${{ github.workspace }}/"
    - name: KLVulkan cat
      run: cat "${{ github.workspace }}/KLVulkan/settings.xml"
    - name: KLVulkan Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -s "${{ github.workspace }}/KLVulkan/settings.xml" --file "${{ github.workspace }}/KLVulkan/pom.xml"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        #now for AGGraphics
    - name: Set up JDK 23 (Again?)
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/AGGraphics # location for the settings.xml file
        
    - name: AGGraphics Build with Maven
      run: mvn -B package --file "${{ github.workspace }}/AGGraphics/pom.xml"
    - name: AGGraphics Test
      run: ls -l "${{ github.workspace }}/AGGraphics/"
    - name: AGGraphics Test2
      run: ls -l "${{ github.workspace }}/"
    - name: AGGraphics cat
      run: cat "${{ github.workspace }}/AGGraphics/settings.xml"
    - name: AGGraphics Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -s "${{ github.workspace }}/AGGraphics/settings.xml" --file "${{ github.workspace }}/AGGraphics/pom.xml"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
#     - uses: actions/checkout@v4
#     - name: Set up Maven Central Repository
#       uses: actions/setup-java@v4
#       with:
#        java-version: '23'
#        distribution: 'temurin'
#        server-id: ossrh
#        server-username: MAVEN_USERNAME
#        server-password: MAVEN_PASSWORD
#        settings-path: ${{ github.workspace }}/KLVulkan # location for the settings.xml file
#     - name: Publish to the Maven Central Repository
#       run: mvn -B deploy -s "${{ github.workspace }}/KLVulkan/settings.xml" --file "${{ github.workspace }}/KLVulkan/pom.xml"
#       env:
#         MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#         MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    
      
